require 'json'
require 'json-schema'

  # default folder for where your schemas reside
if ENV['schemaPath'] == '' || ENV['schemaPath'].nil?
  ENV['schemaPath'] = './schemas'
end

  # default project path to check
if ENV['projectPath'] == '' || ENV['projectPath'].nil?
  ENV['projectPath'] = './'
end

namespace :template do
  desc('validate cloudformation template against schemas')
  task :validate do
    begin
        # iterate over all files in directory
      Dir["#{ENV['projectPath']}/*.json"].each do |f|

          # parse template into map object
        cf_template = JSON.parse(File.read(f))
          # iterate over resources
        cf_template['Resources'].each do |cf_obj|
          next unless File.file?("#{ENV['schemaPath']}/#{cf_obj[1]['Type']}.json")
          begin
              # run json validator
            JSON::Validator.validate!(File.read("#{ENV['schemaPath']}/#{cf_obj[1]['Type']}.json"), cf_obj[1])
            puts "#{cf_obj[1]['Type']}: valid"

              # if validation fails
          rescue JSON::Schema::ValidationError => e
            message = "#{cf_obj[1]['Type']}: invalid #{e}"
            abort message
          end
        end
        puts "#{f}: valid"
      end

      # general exception
    rescue Exception => e
      abort "general error: #{e}"
    end
  end
end
