require 'json'
require 'json-schema'
require 'cfndsl'

  # default project path to check
if ENV['projectPath'] == '' || ENV['projectPath'].nil?
  ENV['projectPath'] = './'
end

namespace :template do
  desc('convert cfndsl cloudformation template to json')
  task :convert do
    begin
      files = []
      Dir["#{ENV['projectPath']}/*.rb"].each do |template|
        files << template.to_s
      end

      extras = []
      Dir["#{ENV['projectPath']}/*.yml"].each do |extraConfigFile|
        extras << [:yaml, extraConfigFile]
      end

      files.each do |f|
        json = CfnDsl.eval_file_with_extras(
          f,
          extras
        ).to_json

        cf_template_new = File.new("#{((File.basename(f).gsub! 'rb', 'json'))}", 'w')
        cf_template_new.puts(json)
        cf_template_new.close

        puts "converted #{f} to json"
      end
    rescue Exception => e
      abort "error: #{e}"
    end
  end
end
